### ISSUE TITLE
Create Performance Evaluation Step 2B - Exit and Cancel Action

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-react#10]
NOTE: This is exactly the same as `Create Performance Evaluation Step 1 - Exit and Cancel Button`

**Description:**

> As an Admin
> I want to be able to cancel the creation process
> so that I can revert in case I made a mistake or the evaluation is no longer necessary

**Acceptance Criteria:**

- [ ] Change button label to CANCEL?
- [x] When cancel button is clicked, display modal window showing a warning message as follows:

```
Are you sure you want to cancel?
If you cancel, your data won't be saved.

```

- [x] Below the message, show NO and YES buttons.
- [x] If NO is clicked, close the modal window
- [x] If YES is clicked, redirect to PERFORMANCE EVALUATIONS List Screen

**Comment by emmaacha** [comment]
PR: #23
