### ISSUE TITLE
Step 2A Clear Button - change color

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#100]
**DESCRIPTION**

- [x] Change color of CLEAR button from RED to WHITE backcolor with purple outline and purple textcolor (same as our other CLEAR buttons). 

![Image](https://github.com/nerubia/kh360-react/assets/1640285/eb084bb4-5485-4bd9-9e38-68353d3fb013)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/103
