### ISSUE TITLE
Step 2A - saved selected employees should be checked by default during editing in Step 2A

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#101]
**DESCRIPTION**

When editing saved Eval Administration, previously saved employees should also be checked by default when loading Step 2A.
E.g. I create new evaluation. Then I select Darwin and Emmalyn as the evaluees. Then I exit and save.

When I go back to this evaluation administration and edit it, when I reach Step 2A, Darwin and Emmalyn should be checked by default.

I think we may need to create a new API (or update the existing API) to retrieve the data from evaluation_results?

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/106
BE: https://github.com/nerubia/kh360-nodejs/pull/86

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/108

**Comment by sheilaramas** [comment]
OK Verified
