### ISSUE TITLE
Evaluations - Eval Admin List

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#104]
**DESCRIPTION**

- [x] When Evaluations from menu is clicked, open Evaluation Administrations List screen. 
- [x] This will display all Evaluation Administrations that the current logged in employee is evaluator of. Do not include those the employee is not part of (as evaluator)
- [x] Only show records whose status is Ongoing (evaluation_administration.status = Ongoing)
- [x] Screen layout to be finalized, for now, use this as reference / inspiration:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/2dd5b9a7-a30c-480c-a87b-f0ce505f6181)

- [x] Remove STATUS column
- [x] Add the following columns:
          - Total Evaluations (total number of evaluation records)
          - Total Submitted
          - Total Pending

- [x] When a row is clicked, go to Evaluations screen showing list of employees for evaluation

**Comment by emmaacha** [comment]
PR: #117

**Comment by sheilaramas** [comment]
OK Verified. Separate ticket created for enhancements.
