### ISSUE TITLE
Eval Admin Step 4 Changes in Layout

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#105]
**DESCRIPTION**

- [x] Is it possible to change the layout to as follows:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/89a8d355-3998-4762-bea2-c46ec24662a8)

- [x] Can you also put more whitespace in between table header and data?

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/107

**Comment by sheilaramas** [comment]
- [ ] Can you add more space in between these rows?


**Current:**



![Image](https://github.com/nerubia/kh360-react/assets/1640285/f8ee057d-ba7d-440d-8352-2ba27e9f3a32)



**Proposed:**



![Image](https://github.com/nerubia/kh360-react/assets/1640285/4965d877-06d7-4f85-ad45-86c1c224a85b)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/114

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/121

**Comment by sheilaramas** [comment]
OK verified
