### ISSUE TITLE
Evaluation Results - Detailed Evaluation issue

### ISSUE THREAD

**Issue by gborgonia-ir** [nerubia/kh360-react#1079]
Investigate why Detailed Evaluation is empty

https://kh360-beta.kaishahero.com/evaluation-results/651

![Image](https://github.com/nerubia/kh360-react/assets/62045758/4ce2f37b-2d80-4be3-b925-34c696c56d4e)

![Image](https://github.com/nerubia/kh360-react/assets/62045758/e59444f1-ecf9-4b86-935b-4d9b2d6b88f1)

**Comment by chadiegilnerubia** [comment]
I will close this ticket because, upon investigation, I discovered that the empty Detailed Evaluation is due to the deletion of the template name, which causes it to return empty
