### ISSUE TITLE
View Evaluation Administration Screen - Extra Blank Record displayed in Employee List

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#111]
**DESCRIPTION**

- When viewing Evaluation Administration Record, there is an extra blank row shown (only comma is displayed).
- Please refer to screen recording below on how to replicate.

https://github.com/nerubia/kh360-react/assets/1640285/229c956e-6eea-413c-8fb1-06de0c71eafd

**Comment by emmaacha** [comment]
PR: #127

**Comment by sheilaramas** [comment]
OK verified
