### ISSUE TITLE
View Eval Admin Issues and Enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#112]
**DESCRIPTION**

- [x] Can you set the Title (Evaluation Administration Name) to purple (similar style to Screen Title)
- [x] Can we revise the layout, please refer to screenshot below.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/6b9962b9-c66e-4e27-95bd-5354920a2e89)

**Comment by emmaacha** [comment]
PR: #126
