### ISSUE TITLE
Eval Admin Step 3 - Can we change badge color for FOR REVIEW

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#113]
**DESCRIPTION**

- [ ] Change from PINK to badge with green outline, green font with white BG (like the opposite of READY)

`CURRENT`

![Image](https://github.com/nerubia/kh360-react/assets/1640285/fbbec3bc-ff57-4790-bd12-e9c1b78e2939)

`PROPOSED`

- something like this but use the READY green color

![Image](https://github.com/nerubia/kh360-react/assets/1640285/90be72e1-a13d-4c67-84af-ffc4f862bf64)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/115

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/116

**Comment by sheilaramas** [comment]
OK Verified
