### ISSUE TITLE
Create Performance Evaluation Step 3 Screen

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-react#12]
**Wireframe:**

![Image](https://github.com/nerubia/kh360-react/assets/54575305/fc25318f-86ba-48bc-afbc-80347b2a1d43)

**Acceptance Criteria:**

- [x] List down all employees that were selected for this Evaluation Group
- [x] By default, display all employees for this evaluation, without filters
- [x] Employees should be sorted by last_name and first_name in ascending order
- [x] Display a maximum of 20 records per page
- [x] When Search button is clicked, display records that match the filters
- [x] When Clear button is clicked, clear all filters then do search function (so all records will be returned)

- [x] Name should be `last_name, first_name` format
- [x] Status to be displayed should be based on `evaluation_results.status`
- [x] When an Employee Row is clicked, redirect to Step 4

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/31
