### ISSUE TITLE
Eval Admin Step 4 - Add header checkbox

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#120]
**DESCRIPTION**

- [ ] Please add a checkbox at the header.
- [ ] When checked, all checkboxes for all rows will be checked.
- [ ] When unchecked, all checkboxes for all rows will also be unchecked.

Sample below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/f1c0d7d7-f734-49b8-9ffe-c89836c006de)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/123
BE: https://github.com/nerubia/kh360-nodejs/pull/95

**Comment by sheilaramas** [comment]
OK verified
