### ISSUE TITLE
Eval Admin Step 2 - Employees were checked in Step 2 even if new record

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#124]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/40ebe932-a905-4194-aa0b-3039cf5c2516)

To replicate, do the following:

1. Open an existing Eval Admin Record and try to edit it.
2. Go back to Eval Admin List to create a new Eval Admin record.
3. Input data in Step 1 and proceed to Step 2.
4. In Step 2, notice that employees are already selected (in this case, the employee selected in step 1 is selected)

https://github.com/nerubia/kh360-react/assets/1640285/24d0fc56-6e8a-4745-83d1-2d2a1cc31312

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/125

**Comment by sheilaramas** [comment]
OK Verified
