### ISSUE TITLE
Investigate issue in prod app not loading

### ISSUE THREAD

**Issue by gborgonia-ir** [nerubia/kh360-react#1298]

**Comment by gborgonia-ir** [comment]
Okay on my end. Able to login in Prod.

@rrosel pls verify on your end and move this ticket, thank you.

**Comment by rrosel** [comment]
**OK in Beta**

[Screenshare - 2024-07-16 2_13_53 PM(1).webm](https://github.com/user-attachments/assets/3bd724af-5a0b-446e-952c-092c129db4ee)
