### ISSUE TITLE
Update Performance Evaluation Screen that can be viewed by External Evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#131]
**DESCRIPTION**

- This is the flow for External Evaluators

- [x] Once the evaluation administration status becomes ongoing, send out email with the passcode to the external evaluators
- [x] External evaluator will receive an email containing the link and the passcode
- [x] Once external evaluator will click on the link, open the Verification Screen (similar to a login screen with email address and textbox where evaluator can input the passcode)
- [x] Include a link in the Verification Screen to resend the email with the passcode
- [x] Set a maximum of 3 tries, if wrong passcode is set, they have to wait for an hour so that they can try again
- [x] If passcode is correct, redirect to evaluations screen

**THINGS TO CONSIDER**

- [x] Link from email must be unique so you can identify which external user is accessing the performance evaluation form
- [x] So you may need to add a token to be included in the link that will identify the user? (i added authentication_token but feel free to change the name if needed)
- [x] You also need a field to store the password or passcode. This is the password field is for but feel free to change the name if needed. Please consider also if we need to encrypt the passcode or not? 
- [x] The failed attempt field is for the number of failed attempts, please feel free to change the field also if you think there is another more appropriate way
- [x] The locked_at is so you can determine what time the user was last locked out
- [x] We will also update the email template and add a placeholder for the passcode if the user is an external user

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/177
BE: https://github.com/nerubia/kh360-nodejs/pull/152

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- [ ] I cannot open the evaluation form. Please refer to screen recording below.



https://github.com/nerubia/kh360-react/assets/1640285/140c01b2-e014-486b-b053-d88d6532beff


- [ ] After the user enters the passcode, you should redirect directly to the evaluation forms
- [ ] Do not display (hide) left menu panel
- [ ] This is a sample on how the screen should look like. The following are not shown:
          - left menu panel
          - burger menu icon
          - back button




![Image](https://github.com/nerubia/kh360-react/assets/1640285/27323a2a-8c28-4450-ab2f-186064b2b0ca)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/221

**Comment by sheilaramas** [comment]
OK verified
