### ISSUE TITLE
Eval Admin List Screen Enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#134]
**DESCRIPTION**

Please do the following enhancements:

- [x] Decrease font size of `results found` from 1.25 to 1rem?
- [x] Add more whitespace between Header Row and Data row
- [x] Sorry, can we remove again the line between header row and data row (now that we will be adding more whitespace)
- [x] Add more whitespace between data rows (same as what we did for Step 4)
- [x] Change number of rows per page from 20 to 10 rows
- [x] For Paging Section, only show this if the data is more than 10 records (more than 1 page)
- [x] For Status, is it possible to display the equivalent badge instead of the text?

**Comment by emmaacha** [comment]
FE PR: #136 
BE PR: [#112](https://github.com/nerubia/kh360-nodejs/pull/112)
