### ISSUE TITLE
Performance Evaluation Form Enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#137]
**DESCRIPTION**

- [x] Please use this concept (hover row)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/f898e13c-7852-4e50-a529-0de69fa3c60b)

- [x] Increase width of left panel
- [x] Increase width of Template Conent / Description Column
- [x] Increase whitespace in between rows
- [x] Add more space between N/A and first star (make it similar to spacing between stars)
- [x] Decrease size of Status Badge
- [x] For Status Badge, use all caps
- [x] Add `SAVE` button
- [x] Change label of `SUBMIT` button to `SAVE & SUBMIT`
- [x] Change implementation, instead of calling API to save data every time a star is clicked, save data only when user clicks either `SAVE` or `SAVE & SUBMIT` button.
- [x] Remove calling API to save when comment is updated. Saving will be done in `SAVE` or `SAVE & SUBMIT` button.
- [x] If the user made any changes to the form without clicking `SAVE` or `SAVE & SUBMIT`, display modal confirmation message whether to discard the changes or not.

**Comment by emmaacha** [comment]
PR: #140

**Comment by sheilaramas** [comment]
**Additional Change Requests**

- [ ] Set font size of criteria from 1.25rem to 1rem


![Image](https://github.com/nerubia/kh360-react/assets/1640285/6061b71e-a643-496f-98ba-12a95bfc6d8f)


- [ ] Increase the spacing in between criteria and N/A (double to what is currently set)


![Image](https://github.com/nerubia/kh360-react/assets/1640285/06303e76-631f-48c3-8884-52a4e0f92206)

**Comment by emmaacha** [comment]
PR: #149

**Comment by sheilaramas** [comment]
OK Verified
