### ISSUE TITLE
Decrease Paging Buttons

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#138]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/0b20640a-1bcc-4a65-8abf-bef8d2125183)

- [x] Can we decrease the size of the paging buttons to 25% less its current size?
- [x] Apply this to all pages with paging

**Comment by emmaacha** [comment]
PR: #141

**Comment by sheilaramas** [comment]
OK
