### ISSUE TITLE
Change EDIT button, add Close and Cancel actions in View Eval Admin Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#146]
**DESCRIPTION**

- Is it possible to change the `EDIT` button below to `ACTIONS`

![Image](https://github.com/nerubia/kh360-react/assets/1640285/3c387cdd-42d7-40a6-8e8d-a89c33939b4a)

- the `ACTIONS` button will act like a dropdown to show what the available actions are for this Eval Admin Record, similar to the button below

![Image](https://github.com/nerubia/kh360-react/assets/1640285/9d12b3c3-a831-4417-97d0-18d936d93b07)

- [x] If status of order = draft, the action available will be EDIT and DELETE
- [ ] If status of order = pending, the action available will only be CANCEL
- [x] if status of ongoing = ongoing, actions available are CLOSE and CANCEL

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/157

**Comment by sheilaramas** [comment]
OK, changed PENDING to allow EDIT also.
