### ISSUE TITLE
Evaluation Form - please fix the left menu panel spacing between rows.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#150]
**COMMENTS**

- [ ] Please fix the spacing in between rows and please add padding as well.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/c17c03e2-ab6f-4c53-965c-a2418d20ae01)

**Comment by emmaacha** [comment]
PR: #149

**Comment by sheilaramas** [comment]
OK verified
