### ISSUE TITLE
In Left Menu Panel, rename Admin to Eval Admin

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#153]
**DESCRIPTION**

- [x] Rename `Admin` menu to `Eval Admin`
- [x] Sample below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/6e29c974-5766-4535-b829-691edcdfc168)

**Comment by emmaacha** [comment]
PR: #163

**Comment by sheilaramas** [comment]
OK, as agreed, use Evaluation Admin
