### ISSUE TITLE
Add External Evaluators List Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#154]
**DESCRIPTION**

- [x] In Left Menu Panel, add `External Evaluators`
- [x] This menu link will only be available to Admins
- [x] When clicked, this will open External Evaluators List
- [x] Search filters are: 
          - Name (like search for last_name, first_name, middle_name)
          - Company (like search)
          - Role (like search)

- [x] Add button to Add External Evaluator (same as Create Evaluations from Evaluation Administration List)

- [x] Columns to be displayed are as follows:
          - Name (`Last Name`, `First Name` `Middle Name`)
          - Email Address
          - Company
          - Role
          - Action Icons (Edit, Delete)

- [x] When `Edit` is clicked, redirect to `Edit External Evaluator` screen
- [x] When `Delete` is clicked:
          - show modal window confirming deletion
          - if YES is clicked, call API to delete record, then show success message (screen must be refresh to show the record is deleted)
          - if NO is clicked, close modal window

**Comment by emmaacha** [comment]
FE PR: [#163](https://github.com/nerubia/kh360-react/pull/163)
BE PR: [#142](https://github.com/nerubia/kh360-nodejs/pull/142)

**Comment by sheilaramas** [comment]
Nothing happens when I click on OK in delete confirmation box.

**Comment by emmaacha** [comment]
PR: #205

**Comment by sheilaramas** [comment]
OK verified
