### ISSUE TITLE
Eval Admin Step 4 Changes related to External Evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#155]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/aba3f85c-8d78-4ccc-8cec-847585fd43bb)

- Do the following:

- [x] Increase whitespace between section header and table (refer to comment in picture above)
- [x] Under External Evaluators section, move the action links to the bottom of the table
- [ ] Rename to `ADD NEW`. When this is clicked, redirect to ADD NEW EXTERNAL EVALUATOR screen. After the admin adds in the new evaluator and redirects back to this screen, this new record must also be added in the list
- [x] Add `ADD FROM LIST` link. When clicked, open EXTERNAL EVALUATORS LIST. This list will be similar to the EXTERNAL EVALUATORS LIST screen but with the following differences:
          - Add as first column the checkboxes. This is to determine which evaluators from the list will be added
          - Remove the last column (action icons for editing and deleting records)
          - Add action button to CANCEL and ADD
          - When CANCEL is clicked, redirect back to Step 4 screen
          - When ADD is clicked, call API to add the checked evaluators to the external evaluators list in Step 4. Redirect to Step 4 and this time, those checked names should be listed as external evaluators

**Comment by emmaacha** [comment]
FE PR: [#172](https://github.com/nerubia/kh360-react/pull/172)
BE PR: [#151](https://github.com/nerubia/kh360-nodejs/pull/151)

**Comment by sheilaramas** [comment]
Disregard the changing of labels for action link (retain add new)
