### ISSUE TITLE
Enhancements for Status Badges

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#158]
**DESCRIPTION**

- Update badge colors for the different statuses

- [ ] Evaluation Administration Status

![Image](https://github.com/nerubia/kh360-react/assets/1640285/653bf97f-5ad2-4d2c-b623-8a5dda70a0ba)

- [ ] Evaluation Results Status

![Image](https://github.com/nerubia/kh360-react/assets/1640285/82036447-e01e-43fb-80b7-16d3b8434f2f)

- [ ] Evaluation Status

![Image](https://github.com/nerubia/kh360-react/assets/1640285/4a5ecf1b-d4c4-4d83-b395-84196992ae92)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/162

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/168
