### ISSUE TITLE
Performance Evaluation Form Changes

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#159]
**DESCRIPTION**

- Sample Design

![Image](https://github.com/nerubia/kh360-react/assets/1640285/8c154ab1-d6e0-4999-bc4a-67fb2d190232)

- [x] Add Evaluee Name (big font)
- [x] Add Project and Role (refer to sample)... If no project, display role or template name (same logic as the left panel) 
- [x] Add Evaluation Period. Font size is smaller than the font used for Project and Role. Change the date format to as follows:
          - for same month and year: mmm dd - dd, yyyy
          - for same year: mmm dd - mmm dd, yyyy
          - for different year: mmm dd, yyyy - mmm dd, yyyy

- [x] Also notice at the left panel, the highlighted portion has no margin on the left side (it sticks to the line at the left side) while at the right side, there is margin or space. Possible to balance this?

**Comment by emmaacha** [comment]
PR: #166

**Comment by sheilaramas** [comment]
**ISSUE**

- [ ] Wrong Eval start and end date. In the screenshot below, correct dates should be Jan 1 - Oct 31, 2023. 


![Image](https://github.com/nerubia/kh360-react/assets/1640285/e3796e12-a4f7-45dd-8b7a-da9d3c7c1e8f)

**Comment by emmaacha** [comment]
PR: #171

**Comment by sheilaramas** [comment]
ok verified
