### ISSUE TITLE
Left Menu Panel Updates

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#160]
**DESCRIPTION**

- Can we try these updates?

![Image](https://github.com/nerubia/kh360-react/assets/1640285/97442062-b479-4724-815b-bc8a9e5e27a8)

- [x] Move the logout button and make it part of the menu list (last item in the list, same as sample above)
- [x] Can we try adding some icons for the other menus since logout has an icon...
          - Dashboard, I cant think or find any from the samples.. is there like a pie graph or bar graph icon?
          - Evaluations, use the star icon
          - Evaluation Administration, use the EDIT icon?
          - External Evaluators, use the person icon

![Image](https://github.com/nerubia/kh360-react/assets/1640285/e8ec3e06-2552-47b3-bd02-4578a38a947e)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/167

**Comment by sheilaramas** [comment]
OK verified
