### ISSUE TITLE
Evaluations List Screen updates

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#161]
**DESCRIPTION**

- Please refer to sample design below.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/53f68374-18a3-468b-b866-c766f6835211)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/165

**Comment by sheilaramas** [comment]
HI @jatnerubia , can you change the backcolor of each row on hover?
Thanks!!!

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/183

**Comment by sheilaramas** [comment]
OK verified
