### ISSUE TITLE
Evaluation Form - require comment if answer is NA

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#170]
**DESCRIPTION**

- [x] In evaluation form, if the evaluator clicks on comment, display message to place comment on why this criteria is NA. (you will be able to know if answer is NA by looking at the answer_type of the answer (answer_type = NA)
- [x] This message box should contain OK button. 
- [x] When OK is clicked, close the message box.
- [x] Change star ratings portion to text box where user can input comments.
- [x] Save this comment when saving or submitting the form.
- [x] Save it in evaluation_rating.comments field.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/d1acfa8a-d68d-495f-8df6-6900f2008f7e)

- [x] For message, get random records from `email_templates` where `template_type = 'Performance Evaluation NA Rating'`

**Comment by emmaacha** [comment]
FE PR: [#185](https://github.com/nerubia/kh360-react/pull/185)
BE PR: [#160](https://github.com/nerubia/kh360-nodejs/pull/160)

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] Possible to widen the pop-up so that the title (subject) can be shown in 1 line?
- [ ] Can you also follow the paragraph breaks? Right now, everything is shown as 1 paragraph.

**Comment by emmaacha** [comment]
FE PR: [#202](https://github.com/nerubia/kh360-react/pull/202)
BE PR: [#186](https://github.com/nerubia/kh360-nodejs/pull/186)

**Comment by sheilaramas** [comment]
Perfect!!!
