### ISSUE TITLE
Evaluation Form - if at least 75% of the answers are the highest rating, please require comment.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#175]
**DESCRIPTION**

- Comment  (evaluation.comment) should be required if the evaluator selects the highest rating for at least 75% of all the criteria.
- Example, if there are 4 criterias to be rated, and evaluator selects highest rating for 3 criterias, then comment should be required.
- You can check if the answer is the highest based if `answer_option.answer_type = 'highest'`
- Steps are as follows:

- [x] Check if 75% or more of the criteria got the highest rating 
- [x] Checking to be done ONLY during SAVE and SUBMIT
- [x] Once SAVE and SUBMIT is clicked, display modal information message with OK button
- [x] Do not allow to proceed unless comment field is filled up

- [x] For message, get random records from `email_templates` where `template_type = 'Performance Evaluation High Rating'`

**Comment by emmaacha** [comment]
FE PR: [#188](https://github.com/nerubia/kh360-react/pull/188)
BE PR: [#168](https://github.com/nerubia/kh360-nodejs/pull/168)

**Comment by sheilaramas** [comment]
Can you set the layout to this way?



![Image](https://github.com/nerubia/kh360-react/assets/1640285/2140260f-a70e-44e0-aadc-86f8740e91db)

**Comment by sheilaramas** [comment]
OK!
