### ISSUE TITLE
Evaluation Form - if at least 75% of the answers are the lowest rating, please require comment.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#178]
**DESCRIPTION**

- Comment  (evaluation.comment) should be required if the evaluator selects the lowest rating for at least 75% of all the criteria.
- Example, if there are 4 criterias to be rated, and evaluator selects lowest rating for 3 criterias, then comment should be required.
- You can check if the answer is the highest based if `answer_option.answer_type = 'lowest'`
- Steps are as follows:

- [x] Check if 75% or more of the criteria got the lowest rating 
- [x] Checking to be done ONLY during SAVE and SUBMIT
- [x] Once SAVE and SUBMIT is clicked, display modal information message (content of message to follow) with OK button
- [x] Do not allow to proceed unless comment field is filled up

- [x] For message, get random records from `email_templates` where `template_type = 'Performance Evaluation Low Rating'`

**Comment by emmaacha** [comment]
FE PR: [#188](https://github.com/nerubia/kh360-react/pull/188)
BE PR: [#168](https://github.com/nerubia/kh360-nodejs/pull/168)

**Comment by sheilaramas** [comment]
Is it possible to set the layout of the message to this? (add linebreaks)



![Image](https://github.com/nerubia/kh360-react/assets/1640285/3d7baa44-9a7d-4db9-ad00-37d119d20794)


Since content is from DB. Maybe we can add some tags? So we can implement linebreaks?

**Comment by emmaacha** [comment]
FE PR: [#202](https://github.com/nerubia/kh360-react/pull/202)
BE PR: [#186](https://github.com/nerubia/kh360-nodejs/pull/186)

**Comment by sheilaramas** [comment]
OK Verified
