### ISSUE TITLE
Evaluation Admin Progress Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#187]
**WIREFRAME**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/1bab02f7-349a-4ccc-b4d1-2d8c4d380e2b)

**OTHER THINGS TO DO**

- [x] Add a BACK button to go back to Evaluation Administration List screen
- [x] Change `Evaluator` to `Evaluators`
- [x] For the layout, follow the layout for View Evaluation Administration (the layout above is just for reference on the information that are needed)

**Comment by emmaacha** [comment]
FE PR: [#208](https://github.com/nerubia/kh360-react/pull/208)
BE PR: [#191](https://github.com/nerubia/kh360-nodejs/pull/191)

**Comment by sheilaramas** [comment]
OK verified, created another ticket for enhancements.
