### ISSUE TITLE
Clicking BACK button when viewing evaluation admin screen should go back to same page where this record is

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#191]
**DESCRIPTION**

- [ ] When viewing evaluation administration then clicking back, it should go back to the page where it currently is. Currently, clicking back returns to first page.

**Comment by jatnerubia** [comment]
dupe of https://github.com/nerubia/kh360-react/issues/190 🤔

**Comment by sheilaramas** [comment]
ok verified
