### ISSUE TITLE
My Evaluations - add new menu link for My Evaluations

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#210]
**DESCRIPTION**

- [x] Add a new menu item, titled `My Evaluations`
- [x] Place this before `Evaluations` menu item
- [x] Rename `Evaluations` to `Evaluation Forms`
- [x] Please think of an appropriate icon for the new menu item (or you can use the star for this and another icon for the evaluation form?
- [x] When this is clicked, redirect to `My Evaluations` screen

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/214

**Comment by sheilaramas** [comment]
OK verified
