### ISSUE TITLE
Checking of 75% High or Low for Performance Evaluation

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#219]
**DESCRIPTION**

This is an enhancement to the following tickets:
- [Evaluation Form - if at least 75% of the answers are the lowest rating, please require comment.#178](https://github.com/nerubia/kh360-react/issues/178)
- [Evaluation Form - if at least 75% of the answers are the highest rating, please require comment.#175](https://github.com/nerubia/kh360-react/issues/175)

- [x] For checking, can you factor in the NA's? Meaning, deduct the number of NA's from the total number of criteria when computing for 75%
- [x] Example:
          - Total number of criteria is 10
          - Evaluator marked 2 criterias as NA
          - So when you compute for 75%, it should now be 75% of the remaining 8 criteria (so if more than 6 are marked as HIGH or LOW, then require comment)

**Comment by emmaacha** [comment]
FE PR: [#245](https://github.com/nerubia/kh360-react/pull/245)
BE PR: [#219](https://github.com/nerubia/kh360-nodejs/pull/219)

**Comment by sheilaramas** [comment]
Was able to submit with 2NA's and 2 5-star ratings.

**Comment by sheilaramas** [comment]
@emmaacha This is correct. There was comment so this should be OK.
