### ISSUE TITLE
Performance Evaluation - we need to show description of the rating

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#220]
**DESCRIPTION**

It might be informative and helpful for the evaluators to know what each star rating means. So we need to display this information in the screen. Will the following implementation be OK (not sure if possible)?
- during hover for each star, display the description (can be found in answer_option.description)

Other suggestions welcome!!!

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/229
