### ISSUE TITLE
Evaluation Form - can we add a Back to List button in this screen to go back to the Active Evaluations List?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#222]
**DESCRIPTION**

- [ ] Can we add a Back to List button in this screen to go back to the Active Evaluations List?
- [ ] Add this in left menu panel... please refer to sample below

![Image](https://github.com/nerubia/kh360-react/assets/1640285/ba597456-6bad-4de4-aa33-bac5d6503aee)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/226

**Comment by sheilaramas** [comment]
OK verified
