### ISSUE TITLE
Evaluation Form - if evaluator has successfully completed the evaluations, display Thank you message pop up

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#223]
**DESCRIPTION**

- [x] If an evaluator has submitted all of his/her evaluation forms, display pop up message saying thanks.
- [x] Content of pop-up to be retrieved from email_templates, with template_type = "Evaluation Complete Thank You Message" and default is 1.
- [x] I will still make the content but can you use temporary for now
- [x] Are there some animations you can implement (e.g. fireworks) or I dont know what is possible lol

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/230
BE: https://github.com/nerubia/kh360-nodejs/pull/204

**Comment by sheilaramas** [comment]
Perfect!!!!

**Comment by sheilaramas** [comment]
**ADDITIONAL ENHANCEMENT**

- [ ] If an evaluator has submitted all of his/her evaluation forms, can we also send email to KH360 admin notifying them that the evaluator has already completed their evaluation for this particular evaluation administration
- [ ]  Content of pop-up to be retrieved from email_templates, with template_type = "Evaluation Complete Thank You Email" and default is 1.
- [ ] I will still make the content but can you use temporary for now

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/281

**Comment by sheilaramas** [comment]
OK verified

**Comment by sheilaramas** [comment]
**CHANGES**

@jatnerubia  please update as follows:

- [ ] For email recipient, please get recipient email from email_recipients where email_type = `KH360 Admin`
- [ ] For timezone, get it from system_settings (default_timezone)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/293

**Comment by sheilaramas** [comment]
ok verified
