### ISSUE TITLE
Update colors of the emojis for My Evaluations

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#227]
**DESCRIPTION**

- Can we use these colors?

![Image](https://github.com/nerubia/kh360-react/assets/1640285/d9d3dc3a-451d-47e2-bf16-8b023f704013)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/256

**Comment by sheilaramas** [comment]
OK Verified
