### ISSUE TITLE
Evaluation Form - please remove error message for NA Comments if evaluator has already filled this up

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#233]
**DESCRIPTION**

- [x] Please remove the error message (and error state) in NA comment if evaluator has inputted data 

![Image](https://github.com/nerubia/kh360-react/assets/1640285/c4e508ac-8787-424a-92db-f3bf4ab15524)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/246

**Comment by sheilaramas** [comment]
OK Verified
