### ISSUE TITLE
Eval Form - We need to add the Template Display name to avoid confusion with possible multiple evaluations with different roles

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#235]
**DESCRIPTION**

- This is a special scenario with Nino being evaluated by Jason Perez (jason evaluating him as Peer and as QA)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/c334108e-5733-4e23-8056-082ce4104f22)

- Currently, it is quite confusing why Jason is evaluating Nino for the same project, on the same duration
- The only difference when you switch between the 2 forms are the criteria but the evaluator is not aware whether he is evaluating him as DEV or as QA (unless the evaluator memorized the criteria for each)

https://github.com/nerubia/kh360-react/assets/1640285/a5c1ff13-671d-470f-8774-eb22aaa4895b

- So given this possible scenario, let's add the Template Display Name in left panel and in Main Panel, same as sample below (if you have other suggestions on how to show this, please feel free to suggest)
- Not much of a fan with the left panel having 3 lines... so other option would be to display the template name on the main panel?

![Image](https://github.com/nerubia/kh360-react/assets/1640285/d831cc45-c0ce-457d-b859-1fbe82544dc7)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/240
BE: https://github.com/nerubia/kh360-nodejs/pull/214

**Comment by sheilaramas** [comment]
OK verified.
