### ISSUE TITLE
Evaluation Progress Screen - Part 2 Enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#238]
**ADDITIONAL ENHANCEMENTS**

- [x] Can we set the order of evaluators to alphabetical order (last name, first name)
- [x] Can we add info on progress of the evaluator (e.g. 3 out or 4 Evaluations Completed).. or maybe the % completed? Can be beside the progress bar before the nudge button?
- [x] In the list of evaluees per evaluator, please change the column heading from `Progress` to `Status`?
- [x] Please widen the columns so that entire evaluee name, template name and other data can be displayed in 1 line. In the screenshot below, there is still a lot of extra space at the right. 

![Image](https://github.com/nerubia/kh360-react/assets/1640285/b4501781-6b04-4cdb-a960-caba6e98ee39)

- [x] Since comments is now taking up space, can just put comment label, then we can expand/collapse the comments? By default, collapse comments.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/92b5ca49-e0a0-4e03-ac70-99b2f60afcd6)

**Comment by emmaacha** [comment]
PR: #258
