### ISSUE TITLE
Evaluation Progress Screen  - add link to Approve or Decline the request to remove

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#241]
**DESCRIPTION**

- Please add the function to be able to Approve or Decline the Request to Remove filed by the evaluator
- Do the following changes in the Admin Progress Screen:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/e90c1c0d-4bbb-4aff-a39a-bd18d188acfc)

- [x] If status is `For Removal`, display Approve | Decline text links (after the status column)
- [x] When mouse is hovered over the For Removal status, can you display the comment (evaluation.comment) as tool tip (same color scheme as the evaluation form tool tip) 
- [x] When clicked, show confirmation message
- [x] For approve, call Approve API
- [x] For Decline, call Decline API
- [x] Display success message ribbon (for both successfully approved or declined operations)
- [x] Update the status of the evaluation record show to reflect either Removed or back to Ongoing status
- [x] If evaluation is Removed, this should not be included as part of the counting for Progress Bar. Example as follows:
          - Given there are 4 evaluations under the evaluator, and currently 2 are Ongoing, 1 is submitted, and 1 is For Review, progress show should be 1 of 4 (or 25%)
          - Once the 4th evaluation request to review is approved, progress should now be 1 of 3 (or 33.33%)

**Comment by emmaacha** [comment]
FE PR: [#272](https://github.com/nerubia/kh360-react/pull/272)
BE PR: [#246](https://github.com/nerubia/kh360-nodejs/pull/246)

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] Status of evaluation is not updated. Only a very small blank status badge is shown. Please see screen recording below.



https://github.com/nerubia/kh360-react/assets/1640285/85c6eefd-da52-4fc7-ba6b-408b6c80e4e7



- [ ] Progress bar and percentage computation are wrong. In given screenshot below, there are 4 evaluations, 1 is removed, 1 is submitted. PRogress should be 33.33% and not 24%



![Image](https://github.com/nerubia/kh360-react/assets/1640285/c7e5553d-0b8d-48b7-8612-965447c05700)

**Comment by sheilaramas** [comment]
**ADDITIONAL COMMENTS**

- [ ] During hover, please adjust tooltip width if comment text is too long. This is what it currently looks like.



![Image](https://github.com/nerubia/kh360-react/assets/1640285/e0f96864-03f7-45a6-92ca-8d5c3233a055)

**Comment by sheilaramas** [comment]
OK verified
