### ISSUE TITLE
Evaluation Form - nothing happens when I click on SAVE and SUBMIT

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#248]
**DESCRIPTION**

- [x] Nothing happens when I click on SAVE and SUBMIT.
- [x] Please refer to screen recording below on how to replicate.

https://github.com/nerubia/kh360-react/assets/1640285/85671753-65ca-412a-a5ae-af71f2db36da

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/249

**Comment by sheilaramas** [comment]
OK verified
