### ISSUE TITLE
Create Performance Evaluation Step 4 - Select Evaluators Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#25]
**Acceptance Criteria:**

- [x] At the left panel, list down all evaluator roles that the selected employee belonged to during the evaluation period (base this on the evaluation templates applicable for the employee). Use DISPLAY NAME field from evaluation_templates.
- [x] Once the admin clicks/selects a role, display the list of evaluators for the employee based on that role.
- [x] By default, the first role is selected
- [x] Display all possible evaluators, no paging for this
- [x] Under first column, display the name of the evaluator. Name should be `last_name, first_name` format.
- [x] Under the second column, display the project name the employee is evaluated for
- [x] Under the third column, display the % assignment of employee
- [x] Under the fourth column, display the duration when the employee was assigned to the project. Format should be yyyy-mm-dd to yyyy-mm-dd.

**Comment by sheilaramas** [comment]
Updated to show changes in screen.



![Image](https://github.com/nerubia/kh360-react/assets/1640285/9eaa7424-a602-4db3-aea9-9615ec7552a5)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/49

**Comment by sheilaramas** [comment]
**ISSUES**

- [ ] Nothing happens when I click on EMPLOYEE EVALUATION on the left. The list of evaluators on the right side were not shown.



![Image](https://github.com/nerubia/kh360-react/assets/1640285/b6e8cbeb-9437-4e3f-8111-502103e7b9d4)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/87

**Comment by sheilaramas** [comment]
OK Verified.
