### ISSUE TITLE
Verification Code Screen - please remove checking for number of characters

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#250]
**DESCRIPTION**

- [x] Same as login screen, you should only be validating on whether the entered code is correct or not. DO not validate if the user entered the correct number of characters.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/999fc925-4522-4751-8284-11abe6ffa40b)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/251
