### ISSUE TITLE
Evaluation Form - please add REQUEST TO REMOVE function

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#253]
**DESCRIPTION**

- Add a feature to allow evaluators to request for the current evaluation form to be excluded from her list
- Please do the following:

- [x] Add button to `Request to Remove` in the lower left portion of the form. Please see sample below. But instead of RED background with white font color, can we do the opposite? (red fontcolor, white backcolor)? this is because the RED button is so catchy and will drag the attention of the evaluators down to the bottom of the screen.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/d48c2db7-a5e6-49e8-88ec-e2ca2d675147)

- [x] This button should only appear if status is either `Open` or `Ongoing`
- [x] Comment is required if this will be removed. So show pop up message requiring comment, with OK button. Once OK is clicked, set focus on the Comment box.
- [x] Display confirmation message saying if they are sure to continue and that ratings will not be saved. (with YES or NO buttons)
- [x] If evaluator will continue, call API to request for removal.
- [x] Once successful, status will change to `For Removal`. This should be displayed at the bottom part of the left panel (after the submitted evaluations) and should no longer be editable. Badge color is orange (please refer to KH360 Specs sheet under Status sheet)

- [x] Please adjust evaluation form list also to include evaluations whose status = `For Removal`

**Comment by emmaacha** [comment]
PR: #257

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] SAVE and SAVE AND SUBMIT buttons are still shown when status is `For Removal`. This should no longer be display (same as SUBMITTED)



![Image](https://github.com/nerubia/kh360-react/assets/1640285/e2e6f7b1-3def-414a-ae54-70c317cd8450)

**Comment by emmaacha** [comment]
FE PR: [#287](https://github.com/nerubia/kh360-react/pull/287)
BE PR: [#255](https://github.com/nerubia/kh360-nodejs/pull/255)

**Comment by sheilaramas** [comment]
ok verified
