### ISSUE TITLE
Evaluation Form - add Recommendations field

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#259]
**DESCRIPTION**

- [x] In Performance Evaluation Form, add a new field for Recommendations
- [x] Add this after Comments Field, please see sample below.
- [x] This will only be displayed if evaluation_template.with_recommendations flag is true. Else, do not show this field.
- [x] Input for this field is not required. Evaluator may leave this blank.
- [x] Save the data under evaluation.recommendations field in the DB.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/f8b08d14-440f-43bb-83b3-5ec91c6a69ea)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/266
BE: https://github.com/nerubia/kh360-nodejs/pull/239

**Comment by sheilaramas** [comment]
OK verified
