### ISSUE TITLE
Eval Admin Step 4 - Mark as Ready Action with no projects set for External Evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#261]
**DESCRIPTION**

- When admin clicks on Mark as Ready and projects are not set for External Evaluators, error message banner is shown below.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/fdaa7724-24d9-4775-bf82-626b094dc357)

- [x] Would it be possible to implement as follows:
          - show the specific evaluation template where the error is occurring.
          - in the screenshot above, the HR Evaluation template is shown but there are no external evaluators there so it may be confusing for the admin user. 
          - So to make it more user friendly, when displaying the error message, can you also switch the template being selected to the one requiring projects to be set for the external evaluator. In this example, this is the template that has external evaluator that needs to be set. 
          - If there are more than 1 templates that has this same error, just show the first one.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/cbc7afa9-847c-451b-9660-9ef29004905a)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/273
BE: https://github.com/nerubia/kh360-nodejs/pull/248

**Comment by sheilaramas** [comment]
OK verified
