### ISSUE TITLE
Eval Admin Step 4 - Enhancements for External Users

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#262]
### **DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/1948bd06-42b8-4ce3-b062-97859e1b8d68)

**CHANGES FOR EVALUATORS TABLE**

- [x] Rename the header text to {{template_display_name}} for {{evaluee_role}} Role
- [x] Remove Roles column (since there is only 1 role per template

**CHANGES FOR EXTERNAL EVALUATORS TABLE**

- [x] Rename the header text to External Evaluators for {{evaluee_role}} Role
- [x] Remove email address (so that columns for the 2 tables will be the same)
- [x] For the email information, can we display this as tool tip when the admin will hover over the external evaluator's name?
- [x] Remove Roles column (since there is only 1 role per template
- [ ] Add column for other project info (% assignment and duration)

**Comment by sheilaramas** [comment]
- [ ] Percentage and Duration should only be populated after the admin has selected a project (since the data here will be based on what the admin selected)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/286
BE: https://github.com/nerubia/kh360-nodejs/pull/254

**Comment by sheilaramas** [comment]
ok verified
