### ISSUE TITLE
Eval Admin Step 4 - admin should be able to add an external evaluator more than once

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#263]
### DESCRIPTION

- In current implementation, the external evaluator can be added only once to the template
- We should allow adding the evaluator multiple times because it is possible he will evaluate for more than 1 project (example, for Nino's case, he has iAssess and PHQ so an external evaluator can also evaluate him for these 2 projects

**Suggested Implementation**

- When loading EXTERNAL EVALUATOR LIST, all evaluators should be unchecked (should not refer to what is currently added)
- So for example, list contains Evaluator1 and Evaluator2. Evaluator1 is checked and ADD button was clicked.
- Evaluator1 is now added as external evaluator.
- Admin again clicks on ADD FROM LIST
- When EXTERNAL EVALUATOR LIST is loaded, the checkboxes must be unchecked 
- If the admin again checks Evaluator1 then clicks on ADD button, Evaluator 1 will now be added again to the External Evaluators list.

**Suggested Validation Options**
Here are some options for validation, other suggestions welcome:

- Upon clicking on ADD button to check max number of times an evaluator can be added (this will be based on how many projects are available for that template.
- Or no checking done on ADD button, but checking will be done when MARK AS READY is clicked?

- Or you can manipulate in the backend. When you load the list for External Evaluators, you can check there how many times an evaluator is added. And if it has reached the max number of times, the name will no longer appear in the list of options.

**Other Things to Take Note of**
- For some templates that are not linked to a project (like employee evaluation or HR Evaluation), external evaluator should only be added once (cannot be added more than once)

**Comment by emmaacha** [comment]
FE PR: [#310](https://github.com/nerubia/kh360-react/pull/310)
BE PR: [#274](https://github.com/nerubia/kh360-nodejs/pull/274)

**Comment by sheilaramas** [comment]
OK verified

**Comment by emmaacha** [comment]
PR: [#298](https://github.com/nerubia/kh360-nodejs/pull/298)

**Comment by sheilaramas** [comment]
OK verified
