### ISSUE TITLE
Evaluation Progress Screen - no evaluations are shown for External Evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#265]
**DESCRIPTION**

- [x] No evaluation records are display for external evaluators.
- [x] Please refer to screenshot below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/6c3dd8fa-600c-4e07-bc1a-c4ecd55276a2)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/16be5229-1bbd-479e-83a8-cac497d43708)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/267
BE: https://github.com/nerubia/kh360-nodejs/pull/241
