### ISSUE TITLE
Evaluation Progress Screen - can we right align Percentage Completed so that the NUDGE buttons will also be aligned?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#275]
**DESCRIPTION**

- [x] Can you adjust percent completed and right justify so that NUDGE buttons will also be aligned

![Image](https://github.com/nerubia/kh360-react/assets/1640285/453093dd-5659-4d78-a07a-1acf99b882bc)

**Comment by emmaacha** [comment]
[#282](https://github.com/nerubia/kh360-react/pull/282)

**Comment by sheilaramas** [comment]
OK verified
