### ISSUE TITLE
Evaluation Progress Screen - possible to not reload the entire page during nudge?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#276]
**DESCRIPTION**

- [x] Would it be possible not to reload the entire page when NUDGE is called? Just call the API in the back-end and display success message without having to reload the entire page?
- [x] Would it also be possible to retain expand/collapse state for each evaluator (e.g. if admin was viewing Racquel Rosel's detailed progress, after NUDGE, it should still be in collapsed state)

Please refer to screen recording below for reference on current implementation.

https://github.com/nerubia/kh360-react/assets/1640285/3839872b-115e-47c3-a17d-d9db4e1e8ba9

**Comment by emmaacha** [comment]
PR: [#282](https://github.com/nerubia/kh360-react/pull/282)

**Comment by sheilaramas** [comment]
ok verified
