### ISSUE TITLE
Badge Color for Eval Admin Status = Processing

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#278]
**DESCRIPTION**

- [x] Please change badge color of PROCESSING status for evaluation administration to orange theme same as below. Right now, it has same color as DRAFT.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/ef90de56-53a6-4844-96b5-5f4179eee90d)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/297

**Comment by sheilaramas** [comment]
OK verified
