### ISSUE TITLE
Eval Admin Step 4 - role is undefined

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#279]
**DESCRIPTION**

- [x] Role is showing as undefined. Please refer to screenshot below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/f8916368-5209-4004-a037-4b8d38b1f155)

- [x] If you are basing it on `evaluation.project_role`, please base it on related project_member.project_role_id (I realized that evaluation does not have a project role). Not sure if this is the cause though.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/283

**Comment by sheilaramas** [comment]
OK verified
