### ISSUE TITLE
Evaluation Form - please fix display if evaluator has a lot of of evaluation forms listed in left panel

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#290]
**DESCRIPTION**

- [ ] Please fix left menu panel below (for scenarios where there is a lot of evaluation forms to be filled up)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/60d7debe-a964-4bb7-a741-107712d839ac)

**Comment by emmaacha** [comment]
[#294](https://github.com/nerubia/kh360-react/pull/294)

**Comment by sheilaramas** [comment]
OKII verified!
