### ISSUE TITLE
External User Login Screen - UI changes

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#291]
**DESCRIPTION**

Can you make the following changes?

- [x] Center align `Resend Verification Code`
- [x] Change font color to purple and underline? (so user will know it can be clicked at one glance) without needed to hover over it.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/fd984441-56c8-4d77-91e8-3d3e71791e53)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/296

**Comment by sheilaramas** [comment]
OK Verified
