### ISSUE TITLE
Evaluation Form - can we widen the form a bit to accommodate more content for description?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#299]
**DESCRIPTION**

- [x] Please widen the main panel of the evaluation form since we will have more description for each criteria. So at least it won't consume much vertical space.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/f0f4337a-12a8-435c-b97b-7830be960a93)

**Comment by emmaacha** [comment]
PR: [#301](https://github.com/nerubia/kh360-react/pull/301)

**Comment by sheilaramas** [comment]
OK Verified
