### ISSUE TITLE
Create Performance Evaluations List Screen

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-react#3]
**Wireframe**

![Image](https://github.com/nerubia/kh360-react/assets/54575305/77b742d3-1a79-4a07-b3b4-115f9f4dceb9)

**Description:**

> As an Admin
> I want to see a list of the Performance Evaluations
> so that I can either view, edit, delete, or view their progress

**Acceptance Criteria:**

- [x] List all evaluations in descending order (latest to oldest)
- [x] Display a maximum of 20 records per page
- [x] By default, no filters are set (so all records will be returned but with pagination implemented)
- [x] When Search button is clicked, display records that match the filters
- [x] When Clear button is clicked, clear all filters then do search function (so all records will be returned)
- [x] When `Create Evaluation` is clicked, redirect to `Create Performance Evaluation` screen

**Upcoming Feature:**
- when NAME is clicked, redirect to VIEW PERFORMANCE EVALUATION screen (this will be worked on once the create administration screens are done)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/19

**Comment by sheilaramas** [comment]
**Comments**

- [ ] Can we decrease the size of the buttons and text? Right now, 100% seems so big
- [ ] Change button color of CLEAR button, to color scheme similar to Cancel (white color with purple font and outline)
- [ ] Can we move the screen title to the top portion of the screen (above the search filters)
- [ ] In place of the screen title, add how many search results there are (see sample below)
- [ ] Can you try adding a line below the column headers? (see sample below)




![Image](https://github.com/nerubia/kh360-react/assets/1640285/4d0a804c-064d-4758-b975-583945b7d56d)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/72

**Comment by sheilaramas** [comment]
**ADDITIONAL COMMENT**

- [ ] For PERIOD and SCHEDULE, `-` should be `to`
          - example: `2023-10-31 - 2023-12-31` should be `2023-10-31 to 2023-12-31`

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/96
BE: https://github.com/nerubia/kh360-nodejs/pull/77
