### ISSUE TITLE
Evaluation Form - fixes and enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#300]
**DESCRIPTION**

- [x] Can we darken the NA button (for submitted or Request to Remove Evaluations).. maybe color sa purple sa star? Please show me what it looks like before final implementation
- [x] Comments for NA not show (not sure why)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/ab537904-01cc-43ff-86c5-23993f8e832b)

**Comment by emmaacha** [comment]
PR: [#301](https://github.com/nerubia/kh360-react/pull/301)

**Comment by sheilaramas** [comment]
ok verified
