### ISSUE TITLE
Eval Admin Step 4 - Add an [Add Evaluator] button

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#304]
**DESCRIPTION**

- [x] Add button labeled `Add Evaluator`.
- [x] When clicked, redirect to the new Add Evaluator screen.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/bb7679bf-cbb9-47dd-b029-c771461198a0)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/313

**Comment by sheilaramas** [comment]
ok verified
