### ISSUE TITLE
Eval Progress Screen - please hide NUDGE button if eval_admin status is CLOSED, PUBLISHED or CANCELLED

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#308]
**DESCRIPTION**

- [ ] Please hide NUDGE button if status is CLOSED, PUBLISHED or CANCELLED

![Image](https://github.com/nerubia/kh360-react/assets/1640285/132b5053-1d70-4362-9c75-37824caf9d18)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/309

**Comment by sheilaramas** [comment]
ok verified
