### ISSUE TITLE
Login Screen - can you put somewhere in the screen the text KH360 so users will know they are logging in to KH360 App?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#316]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/a4d5f503-e412-439d-8027-c326f68e6866)

- Can you put somewhere in the screen KH360 so that they will know the login screen is for KH360?

**Comment by emmaacha** [comment]
PR: #326

**Comment by sheilaramas** [comment]
ok verified
