### ISSUE TITLE
Eval Form - can you adjust the margins for the highlighted criteria?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#319]
**DESCRIPTION**

- [x] Can you a little padding/margin (sorry don't know the appropriate term) for the row highlight? Right now, there is no margin or padding in the left and right sides.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/dc403569-854c-40d9-b8c7-a359c25cb99f)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/322

**Comment by sheilaramas** [comment]
ok verified
