### ISSUE TITLE
Evaluation Form - Evaluation Completed Thank you Message Popup

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#320]
**DESCRIPTION**

- [x] Can we have separate thank you message for Internal vs External Evaluators?
- [x] For internal evaluators, please use the same template type = `Evaluation Complete Thank You Message`
- [x] For external evaluators, let's use the template type = `Evaluation Complete Thank You Message External`

![Image](https://github.com/nerubia/kh360-react/assets/1640285/7cf66898-09cd-419a-aee4-55f608975c66)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/321

**Comment by sheilaramas** [comment]
OK verified
