### ISSUE TITLE
External Evaluator - should not be able to add external evaluator if deleted

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#323]
### **DESCRIPTION**

- [x] If an external evaluator is already deleted, you should not be able to add them to evaluations. 
- [x] Currently, soft-deleted external evaluators are still shown on the options. Please see sample below:

**ADDING FROM EXTERNAL EVALUATOR LIST**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/58f12745-073a-4592-bc2b-115c2743d8b3)

**MANUALLY ADDING A NEW EVALUATOR**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/68c88b5b-0525-403c-9780-ce586de56d73)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/296

**Comment by sheilaramas** [comment]
ok verified

**Comment by rrosel** [comment]
**Verified OK in Beta**


https://github.com/nerubia/kh360-react/assets/54173000/1839a9a8-cc1d-40e7-8d97-57bdf7b39dd8
