### ISSUE TITLE
Adding Evaluator - when adding evaluator manually, can you set the default value of the template dropdown based on what was currently selected?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#331]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/c59a81c5-1db9-453a-ac77-7ead8afc8b09)

**Comment by emmaacha** [comment]
PR: #334

**Comment by sheilaramas** [comment]
OK verified

**Comment by Acey06** [comment]
Verified OK on my end in Beta

- Add Evaluator
https://github.com/nerubia/kh360-react/assets/26914098/f06528a0-ad0c-4117-a8be-dc8525015ab4

- Add New
https://github.com/nerubia/kh360-react/assets/26914098/6b5af3e1-6d8b-4551-b11a-961de70d97cd
