### ISSUE TITLE
Eval Admin Step 4 - need to be able to edit the Project for external user

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#336]
**DESCRIPTION**

- Actual User Scenario: I made a mistake in selecting the project for the evaluator and cannot correct it.
- So let's add a feature to allow user to edit. Suggestion is as follows:

- [x] Make Project Name clickable (either hyperlink or button). When clicked, display the available projects admin can choose from. (or if you have any other suggestion, please feel free to suggest)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/1f11cb28-0e5d-485e-b4dc-fdfed22cb17c)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/339

**Comment by sheilaramas** [comment]
OK verified but there is a related issue, created ticket for this #
