### ISSUE TITLE
Eval Progress Screen - we may need to find a way to show the evaluation period

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#337]
**DESCRIPTION**

- Actual scenario: hard to distinguish the evaluation records with the same project and template (because the dates are not shown which is the only thing different)
- Can we find a way to show the dates?
- Options (feel free to suggest):

- [ ] Add another column showing the dates
- [ ] Display the evaluation information in the tool tip (for this approach, we may need to display at least the Project Name, Duration then the comments)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/2ab74db7-8a48-4e4e-a9f7-3418d863255f)

**Comment by emmaacha** [comment]
PR: #338

**Comment by sheilaramas** [comment]
OK verified
