### ISSUE TITLE
Eval Form - please increase max length of NA comments to 500 characters

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#343]
**DESCRIPTION**

- [x] Please increase max length of NA comments to 500 characters
- [x] Please make sure also that the display is OK with 500 characters (for submitted evaluation forms)

**Comment by emmaacha** [comment]
PR: [#318](https://github.com/nerubia/kh360-nodejs/pull/318)

**Comment by sheilaramas** [comment]
ok verified
