### ISSUE TITLE
Eval Admin Progress - we need to put an indicator for Project Name so Admin will have an idea info can be shown on hover?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#344]
**DESCRIPTION**

- [ ] Maybe we can put a calendar icon as a guide to the admin that you can hover on it to view the dates?

![Image](https://github.com/nerubia/kh360-react/assets/1640285/22dce259-91ec-469a-9baa-1a0b85043bae)

**Comment by emmaacha** [comment]
PR: #359

**Comment by sheilaramas** [comment]
ok verified
