### ISSUE TITLE
Add External Evaluator - after inputting project, the project buttons disappeared.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#348]
**DESCRIPTION**

- Project button disappears after selecting a project.
- I think this happens if the project is the last project left.
- For 1st screen recording, since HC is the only project, after selecting HC, it disappears.
- For 2nd scenario, button works fine for the first few projects. But when there is only 1 project left in the options, after selecting that project, all buttons disapper.

https://github.com/nerubia/kh360-react/assets/1640285/6fc42646-8ac1-4bd2-a634-513582df1c5e

https://github.com/nerubia/kh360-react/assets/1640285/2e8445a9-5ac3-4928-91fc-e8729edde2d0

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/366

**Comment by sheilaramas** [comment]
ok verified
