### ISSUE TITLE
Add External Evaluator - remove % when adding external evaluator with no project

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#350]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/06618480-ab90-4498-a28c-b5a193b7a88a)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/366

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- Confirmed % is no longer appearing for templates with no project.
- But there is another new issue, not sure if side effect of this fix (or for another fix) but just placing this here. 


- [ ] When adding external evaluators for non project related templates (e.g. HR Evaluation and PM Evaluation), project button should not appear. Now it is appearing. 



![Image](https://github.com/nerubia/kh360-react/assets/1640285/619299a9-d902-4d88-b9d0-7f65420898c5)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/412

**Comment by sheilaramas** [comment]
ok verified

**Comment by rrosel** [comment]
**Verified OK in Beta**
![image](https://github.com/nerubia/kh360-react/assets/54173000/f048a307-eaf5-4a12-8ab5-0dc48356c1b6)
