### ISSUE TITLE
Evaluation Results - add new menu item for Evaluation Results

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#351]
**DESCRIPTION**

- [x] Add new menu item for `Evaluation Results`
- [x] This will only be available to users whose user_detail.user_type = `BOD`
- [x] Place this menu item after `Evaluation Forms`
- [x] When clicked, open to `Evaluation Results List` screen (new screen) - this screen will still be created

**Comment by emmaacha** [comment]
#362

**Comment by sheilaramas** [comment]
**POSSIBLE ISSUE / FOR INVESTIGATION**

- If I am the one who logs in (sheila@nerubia.com), I can click on Evaluation Results and I am redirected to Evaluation Results screen which is what is expected. 
- But if I log out and switch to another user (still BOD) - sheila+kh360+aaron@nerubia.com, when I click on Evaluation Results, I am redirected to the dashboard link `https://kh360-beta.kaishahero.com/dashboard` and shown NOT FOUND error instead of the evaluation results screen.
- Please refer to screen recording below for reference.



https://github.com/nerubia/kh360-react/assets/1640285/363a38af-0471-4615-b8c4-8df760cc24fa

**Comment by emmaacha** [comment]
FE PR: [#377](https://github.com/nerubia/kh360-react/pull/377)
BE PR: [#351](https://github.com/nerubia/kh360-nodejs/pull/351)

**Comment by sheilaramas** [comment]
**ENHANCEMENTS**

- Aside from `user_detail.user_type = BOD` user who can view this Menu Item, please also allow the CM to view the results with the following conditions (all conditions must be met):

- [ ] User is a CM

**Comment by emmaacha** [comment]
PR: #389

**Comment by sheilaramas** [comment]
This is not yet implemented, please implement:

User has khv2_cm -> for this role, user can see the evaluation results of those under him/her
Example: If Emma logs in, she should only see Emmalyn and Darwin in the results (since she is their CM).
Currently, she can see all results.




![Image](https://github.com/nerubia/kh360-react/assets/1640285/0a8b3c56-7370-4043-b458-45b7b8f12b47)

**Comment by emmaacha** [comment]
Done ^^

**Comment by sheilaramas** [comment]
ok verified..
