### ISSUE TITLE
Create Evaluation Results screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#352]
**DESCRIPTION**

- This screen will be available for BOD's and CM's who will review the overall results
- Screen will be similar to the new `My Evaluations` with the following changes (refer to comments with RED FONT):

![Image](https://github.com/nerubia/kh360-react/assets/1640285/e17d044f-9f5c-4a16-a9cb-2e5e5932ffa7)

- Details per Evaluation Template will be the same (no change)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/376299bc-9ea9-4983-866b-d2d86ef44847)

**Comment by sheilaramas** [comment]
**ADDED NOTES**

- There will be an additional section (to be displayed before total score) but specs will be in another ticket.

**Comment by emmaacha** [comment]
FE PR: [#386](https://github.com/nerubia/kh360-react/pull/386)
BE PR: [#356](https://github.com/nerubia/kh360-nodejs/pull/356)

**Comment by sheilaramas** [comment]
Evaluation Results screen not shown :(



![Image](https://github.com/nerubia/kh360-react/assets/1640285/06b860c1-cfee-4ad0-a47e-e1d25603d990)

**Comment by emmaacha** [comment]
PR: [#365](https://github.com/nerubia/kh360-nodejs/pull/365)

**Comment by sheilaramas** [comment]
OK Verified. Creating separate ticket for enhancements.

**Comment by Acey06** [comment]
No result drawings for result:
1. **Anor, Darwin** 
Testing for Scores Computation Part 3
Jan 2 - Dec 8, 2023
2. **Anor, Darwin**
Testing for NA
Jan 1 - Nov 30, 2023
![image](https://github.com/nerubia/kh360-react/assets/26914098/920867e6-06a2-44a7-9635-1a02a8c348e2)

**Comment by Acey06** [comment]
Verified OK

Issue no. 1 is an old data only
Issue no. 2 is created another ticket
