### ISSUE TITLE
Create Evaluation Results List screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#353]
**DESCRIPTION**

- This screen will be similar to `Evaluation Forms` list screen
- Please refer to sample below

![Image](https://github.com/nerubia/kh360-react/assets/1640285/97e6895b-3946-41aa-b734-e7070c45ba2a)

- Data to be displayed are as follows:

- [ ] Evaluation Administration Name
- [ ] # of Evaluees (Change text to `{{evaluation_results_count}} Evaluation Results`)
- [ ] Evaluation Period
- [ ] Comments (no need to set the label to bold)

- When one of the rows are clicked, redirect to Evaluation Results screen

**OTHER CHANGES**

- use same vertical margins/spacing for the #of evaluees, evaluation period and comments

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/363

**Comment by sheilaramas** [comment]
Closing this, this is changed to a new screen.
