### ISSUE TITLE
Create a new menu item `KH360 Admin`

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#354]
**DESCRIPTION**

- [x] Add new menu item for `KH360 Admin`
- [x] This will only be available to users who has `kh360` role under user_roles 
- [x] Place this menu item after `Evaluation Forms`
- [x] When clicked, open sub-menu to contain the following:
          - Evaluation Administration
          - External Evaluators
          - Project Assignments

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/360

**Comment by sheilaramas** [comment]
**ENHANCEMENTS**

- [ ] Can we adjust so that the `Project Assignments` menu item can be displayed in 1 line? Either:
          - widen the menu a bit?
          - or decrease the font size for sub menus
          - any other suggestions?



![Image](https://github.com/nerubia/kh360-react/assets/1640285/d02ef871-b5f9-483d-869c-4e7f7ada2491)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/375

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- Verified for the adjustments in font to display everything in 1 line
- Additional question: It seems like the screen flickers the first time this menu is clicked. Is is possible to remove this flicker like behavior? (in the screen recording below, it is quick but there are cases which I was not able to capture wherein it is slow so it seems like the entire screen is reloaded)



https://github.com/nerubia/kh360-react/assets/1640285/620de3ec-46f0-4498-af17-259a6923249f

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/409

**Comment by sheilaramas** [comment]
ok verified
