### ISSUE TITLE
Evaluation Form - can we display also the answer display name in the tooltip?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#355]
**SAMPLE SCREEN**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/abd5ed61-e624-4089-8ca6-a8ef8ab831f8)

- [ ] For the title, use answer_option.display_name

**Comment by emmaacha** [comment]
PR: #358

**Comment by sheilaramas** [comment]
ok verified
