### ISSUE TITLE
Evaluation Forms - can you check the cause for broken images for some evaluators?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#356]
**DESCRIPTION**

- Right now, some of the images for the employees are broken. Please see screenshot below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/e8f9b296-d5b8-4e17-91a1-f4e555b70a82)

- Can you check the cause?
- Is it possible for these records to show a default image instead? e.g. initials of their first name same as the others?

**Comment by Dev-Nino** [comment]
It seems that the image cannot be accessed.
<img width="778" alt="Screenshot 2023-12-18 at 10 43 23 AM" src="https://github.com/nerubia/kh360-react/assets/12960397/34cee8c2-32b1-46b8-8637-e1c14c699f9d">

**Comment by Dev-Nino** [comment]
PR: https://github.com/nerubia/kh360-react/pull/361

**Comment by sheilaramas** [comment]
@Dev-Nino , can you adjust the back color and use a lighter shade of grey?



![Image](https://github.com/nerubia/kh360-react/assets/1640285/9c882f2c-2054-4268-a689-87c13ff7ad07)

**Comment by Dev-Nino** [comment]
Yes, sure @sheilaramas

**Comment by Dev-Nino** [comment]
@sheilaramas , how about this one?
![Image](https://github.com/nerubia/kh360-react/assets/12960397/335da1cb-0571-4b37-917f-1522c1c385a4)

**Comment by Dev-Nino** [comment]
PR: https://github.com/nerubia/kh360-react/pull/369
