### ISSUE TITLE
Eval Progress Screen - display data for email logs for reminder emails

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#364]
**DESCRIPTION**

- [x] Add a tool tip when admin hovers over the nudge button
- [x] Display the information when the reminders where sent out
          - when no reminders were sent out previously, just display `No reminders sent.`
          - if there are reminders, display as follows:

- If 3 or less sent out:
```
{{number of reminders}} reminders sent. Reminders sent last:
- Dec 10, 2023 at 4:00PM
- Dec 8, 2023 at 10:30AM
```

- If more than 3 sent out:
```
{{number of reminders}} reminders sent. Latest reminders sent last:
- Dec 10, 2023 at 4:00PM
- Dec 8, 2023 at 10:30AM
- Dec 5, 2023 at 12:00AM
View More
```

- [x] If `View More` is clicked, show modal window displaying all the times the reminders were sent out
- [x] When listing down the dates and times (for both tool tip and modal pop-up), display the dates in descending format (latest first)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/370
BE: https://github.com/nerubia/kh360-nodejs/pull/337

**Comment by sheilaramas** [comment]
**ENHANCEMENTS**

- [ ] If only 1 reminder send, please use singular form (e.g. `1 reminder sent.`)



![Image](https://github.com/nerubia/kh360-react/assets/1640285/ea8fe32a-f0de-4b8c-b687-39fa25da1af5)


- [ ] For more that 3 sent out, can you change instead of button, use `View More` as a text link?


![Image](https://github.com/nerubia/kh360-react/assets/1640285/da3c73d7-2153-444b-9afb-f9a892730962)


- [ ] Date and times shown must be converted to user's timezone. Currently, what is shown is UTC time.

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/378
BE: https://github.com/nerubia/kh360-nodejs/pull/350

**Comment by sheilaramas** [comment]
**DESCRIPTION**

- [ ] Please implement this -> `use View More as a text link with same font size as the rest of the text?`

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/405

**Comment by sheilaramas** [comment]
OK verified
