### ISSUE TITLE
My Evaluaton Results - Enhancements Revision 1

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#368]
**DESCRIPTION**

- Please see sample below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/0a74eac2-54f0-41e6-ae99-5209ec1a6cbc)

- [ ] We also need to add details per Evaluation Template. Sample look below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/376299bc-9ea9-4983-866b-d2d86ef44847)

**Comment by emmaacha** [comment]
FE PR: [#382](https://github.com/nerubia/kh360-react/pull/382)
BE PR: [#353](https://github.com/nerubia/kh360-nodejs/pull/353)

**Comment by sheilaramas** [comment]
Hello @emmaacha , can you check if this is in Beta already?



https://github.com/nerubia/kh360-react/assets/1640285/10848561-8f67-4e21-adc9-1267dd1715f6

**Comment by emmaacha** [comment]
Yes ate Shei, but there's a bug regarding score ratings, will be looking into this.

**Comment by emmaacha** [comment]
FE PR: [#401](https://github.com/nerubia/kh360-react/pull/401)
BE PR: [#365](https://github.com/nerubia/kh360-nodejs/pull/365)

**Comment by sheilaramas** [comment]
ok verified, will create separate ticket for additional enhancements
