### ISSUE TITLE
Create Distribution Chart for Evaluation Results

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#384]
**DESCRIPTION**

- Add Distribution Chart link in Evaluation Results Screen (put this before Comments section)
- When clicked, show expanded view displaying the Distribution Chart
- This chart will contain list of all evaluators of the Evaluee being viewed along with the zscore results of everyone he/she evaluated for the administration period
- Please see sample content of the chart below. No need to follow exact design as this was just made to show the components of the graph and what the data to be displayed is. 

![Image](https://github.com/nerubia/kh360-react/assets/1640285/344b90b8-6a61-4bdf-9927-5b112dd24f12)

**Comment by emmaacha** [comment]
PR: #393

**Comment by emmaacha** [comment]
FE: #407 
BE: [#369](https://github.com/nerubia/kh360-nodejs/pull/369)

**Comment by sheilaramas** [comment]
ok verified!
