### ISSUE TITLE
Display Attendance and Punctuality Information for Evaluation Results

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#385]
**DESCRIPTION**

- Add the Attendance and Punctuality Table between Detailed Results and Comments. 
- Please see sample below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/4cd3dbe2-7594-4f79-8e64-8c9bd63964f5)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/391

**Comment by sheilaramas** [comment]
**ADDITIONAL CHANGES**

- [ ] Change label of `# of Other` to `# of Other Leaves`
- [ ] Add a new column after `#of Unpaid Leaves`. Title is `# of Unfiled Leaves` and compute this by `# of days present - total number of leaves for all types of leaves`

**Comment by sheilaramas** [comment]
Sorry, for # of Unfiled Leaves, please change formula. Correct one is: 
`# of working days  - # of days present - total number of leaves for all types of leaves`

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/373

**Comment by sheilaramas** [comment]
ok verified
