### ISSUE TITLE
Evaluation Form - names and other info on header is no longer displayed

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#394]
**DESCRIPTION**

- [ ] Name and the rest of the info are no longer displayed.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/0593e3b8-de3f-49fd-b9e1-f1e819cea169)

**Comment by emmaacha** [comment]
[#364](https://github.com/nerubia/kh360-nodejs/pull/364)

**Comment by sheilaramas** [comment]
ok verified
