### ISSUE TITLE
Eval Form - add delete icon for external evaluators

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#395]
**DESCRIPTION**

- [x] Can we add a delete icon as the last column for external evaluators? 
- [x] When clicked, delete from the screen and also delete the evaluation record created for that row.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/53c6b73f-b6f2-4b9e-8b6d-f537578ab861)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/414
BE: https://github.com/nerubia/kh360-nodejs/pull/376

**Comment by sheilaramas** [comment]
ok verified
