### ISSUE TITLE
Eval Progress Screen - is it possible to display updated number of reminders after NUDGE button is clicked?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#396]
**DESCRIPTION**

- [x] Currently, we have to refresh the screen so that info on how many times the evaluator is reminded is updated. Please refer to screen recording below.
- [x] Is it possible to automatically update so that after the NUDGE button is clicked and the reminder email is sent out, once we hover on the button, the updated info is shown (e.g.g from 0 reminders sent to 1 reminder sent)?

https://github.com/nerubia/kh360-react/assets/1640285/669164f0-dde3-458c-a7c7-4249367ed03d

**Comment by emmaacha** [comment]
FE: [#408](https://github.com/nerubia/kh360-react/pull/408)
BE: [#370](https://github.com/nerubia/kh360-nodejs/pull/370)

**Comment by sheilaramas** [comment]
OK verified
