### ISSUE TITLE
Create View Evaluation Administration Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#40]
**WIREFRAME**

- DRAFT STATUS

![Image](https://github.com/nerubia/kh360-react/assets/1640285/ea02c0b6-ee4c-4f4b-b3b3-d9af77499375)

- ADMINISTERED (OPEN OR ONGOING) STATUS

![Image](https://github.com/nerubia/kh360-react/assets/1640285/07a5e3c6-9a47-4cbc-ab1c-d8db3bd82c3d)

**Comment by sheilaramas** [comment]
**ACCEPTANCE CRITERIA**

- If evaluation_administration.status = `Draft`
     - [ ] Edit button will be visible and clickable
     - [ ] Progress button will not be visible (hidden)
     - [ ] Edit Employees button will not be visible (hidden)

- If evaluation_administration.status = `Pending` or `Ongoing`
     - [ ] Edit button will be visible and clickable
     - [ ] Progress button will be visible and clickable
     - [ ] Edit Employees button will be visible

- If evaluation_administration.status = `Closed` or `Cancelled`
     - [ ] Edit button will be visible and clickable
     - [ ] Progress button will be visible and clickable
     - [ ] Edit Employees button will not be visible (hidden)

**Comment by emmaacha** [comment]
PR: #59

**Comment by sheilaramas** [comment]
**ADDITIONAL CHANGES AND ISSUES**



![Image](https://github.com/nerubia/kh360-react/assets/1640285/13fa3b54-33a4-4b75-9355-d3088d6a771c)


- [ ] The `x` button (on the upper right hand side) is not implemented. Just change this `x` to a BACK button at the lower left (same design as the other back buttons we have). If clicked, redirect back to the list screen.
- [ ] Wrong dates shown for Evaluation Schedule (in screenshot above, `Oct 31, 2023 to Nov 29, 2023` is shown (please refer to screenshot below for DB data)
- [ ] Wrong dates shown for Evaluation Period (in screenshot above, `Dec 31, 2022 - Jun 29, 2023` is shown (please refer to screenshot below for DB data)


- [ ] Add a `DELETE` button. 
           - Use the RED button for this. 
           - Put this button after EDIT button
           - This should only be shown if status is `DRAFT`. 
- [ ] When `DELETE` button is clicked:
          - show modal message "Are you sure you want to delete this record? This action cannot be reverted." 
          - Display NO and YES buttons
          - When NO is clicked, close modal window
          - If yes is clicked, call API to delete.

- [ ] Transfer PROGRESS button before EDIT button (left side of EDIT button). So new order of buttons will now be [ PROGRESS, EDIT, DELETE)



![Image](https://github.com/nerubia/kh360-react/assets/1640285/52abddb3-8173-40db-9bf4-c2dfc52e6af8)

**Comment by emmaacha** [comment]
PR: #119

**Comment by sheilaramas** [comment]
Verified all changes, additional comments to be included under a new ticket.
