### ISSUE TITLE
Edit External Evaluator - when editing external evaluator record, ROLE and Company fields are not populated.

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#421]
**DESCRIPTION**

- When editing external evaluator, the ROLE and Company fields are blank (data from DB are not retrieved).
- Please refer to screen recording below.

https://github.com/nerubia/kh360-react/assets/1640285/3c7d42ad-701d-4bd3-99ae-428419209ee0

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-nodejs/pull/387

**Comment by sheilaramas** [comment]
ok verified

**Comment by rrosel** [comment]
**Verified OK in Beta**

![image](https://github.com/nerubia/kh360-react/assets/54173000/3a35e245-18ad-42dc-8716-466b2f0adeab)
