### ISSUE TITLE
Eval Progress Screen - hard to click on VIEW MORE

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#422]
**DESCRIPTION**

- [x] Can you find any way so it will be easier for user to click on VIEW MORE link? Open to ideas (alternate options other than using tool tip).. 
- [x] Right now, it is hard to find exact way for the tooltip not to disapper so we can click in VIEW MORE 😂
- [x] Please refer to screen recording below.

https://github.com/nerubia/kh360-react/assets/1640285/e67a9f93-b493-4055-8c27-00868cb19ad4

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/432

**Comment by sheilaramas** [comment]
ok verified
