### ISSUE TITLE
Evaluation Result - Redirection Issues

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#425]
**DESCRIPTION**

- [x] When clicking BACK button, it redirects to `My Evaluation List` screen... it should redirect to `Evaluation Results List`
- [x] Also when clicking BACK, please redirect to the screen or page where it currently is. Also retain the search results. Example, if I selected to filter based on Evaluation Administration, with 3 pages and I view a record from 2nd page, after viewing the record and clicking on BACK, it should redirect me back to page 2 with the results still filtered based on Evaluation Administration

**Comment by emmaacha** [comment]
PR: [#429](https://github.com/nerubia/kh360-react/pull/429)

**Comment by sheilaramas** [comment]
ok verified

**Comment by Acey06** [comment]
Questions:
1. Logout & Login, the back button behavior should be still working?
2. Every click back button, the data of last page of eval result will reflect a second before the prev page will display. Is it OK?

**Comment by Acey06** [comment]
All questions has been answered and as is all.

Verified OK
