### ISSUE TITLE
Increase session time in live to at least 5 hours

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#492]

**Comment by sheilaramas** [comment]
@rrosel  please test in live (at least 2 hrs)

**Comment by rrosel** [comment]
**Verified OK in Beta**

Paused time - 3:12PM

https://github.com/nerubia/kh360-react/assets/54173000/14f8e2ee-9b11-4836-92b0-17c3634a4564

Resumed time - 5:45PM

https://github.com/nerubia/kh360-react/assets/54173000/fb3ecee9-5198-46de-a462-87d555746721
