### ISSUE TITLE
Create Performance Evaluation Screen (Step 1)

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-react#5]
**Description:**

> As an Admin
> I want to generate evaluation forms
> so that the employees' performance can be assessed

**Wireframe:**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/24a77f2a-12d7-4842-9f2d-6b6d252467e1)

**Acceptance Criteria:**

- [x] The following fields are required:
            - Evaluation Name
            - Evaluation Period (from and to)
            - Evaluation Schedule (from and to)
            - Email Subject
            - Email Content

- [x] If required fields are left blank, set fields to error state and display error note
- [x] Date format should be yyyy-mm-dd
- [x] Date Duration or Period format should be yyyy-mm-dd to yyyy-mm-dd
- [x] Evaluation Period from should not be later than Evaluation to
- [x] Evaluation Schedule from should not be later than Evaluation to
- [x] Evaluation Period must not be later than Evaluation Schedule
- [x] When you click SAVE and PROCEED, save data and redirect to Step2

**Comment by emmaacha** [comment]
PR: #17

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] Please put screen title at top (Create Evaluation). Use purple font color for this (same as button color)
- [ ] Duplicate `Evaluation Name` text, I think the first one is meant for the title?
- [ ] Change `Evaluation description/notes` label to `Description`

**Comment by emmaacha** [comment]
PR: #78

**Comment by sheilaramas** [comment]
![Image](https://github.com/nerubia/kh360-react/assets/1640285/ea93a3cc-bb26-4668-a349-397d3ce1ac69)

- [ ] Use same font settings as `Description` for Evaluation Name, Period and Schedule (refer to picture above)
- [ ] Under Email Section, please add label for Content (use `Content`).. for the placeholder text, please put `Email Content` and not `Some Description`

**Comment by emmaacha** [comment]
PR: #83
