### ISSUE TITLE
Create Performance Evaluation Step 4 - Employee Carousel

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#54]
**WIREFRAME**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/5656ec57-deda-46f6-85dc-e52686f9858a)

**ACCEPTANCE CRITERIA**

- [x] ` < ` button should be disabled (or hidden) if current employee is the first employee
- [x] ` < ` button should be enabled if current employee is not the first employee  
- [x] ` > ` button should be disabled (or hidden) if current employee is the last employee
- [x] ` > ` button should be enabled if current employee is not the last employee  
- [x] Display photo of the employee
- [x] Display the Name using 'last_name', 'first_name' format
- [x] Display the 'evaluation_results.status' of the employee below the name

**EVALUATION RESULTS STATUS REFERENCE**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/7578d551-b0c3-4bfd-bc1a-45941f1990af)

**Comment by jatnerubia** [comment]
FE: https://github.com/nerubia/kh360-react/pull/63
BE: https://github.com/nerubia/kh360-nodejs/pull/53

**Comment by sheilaramas** [comment]
Separate ticket to be created for changes in layout.
