### ISSUE TITLE
Create Performance Evaluation Step 4 - Save as Draft Action

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#55]
**ACCEPTANCE CRITERIA**

- [x] When clicked, call the API to save the data in Step 4, setting the status to DRAFT
- [x] If operation is successful, redirect to STEP 3 screen (employee list)
- [x] If error occurs, display error message

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/64
