### ISSUE TITLE
Create Performance Evaluation Form

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#60]
**Wireframe:**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/a86064d3-5bf5-4e7a-8c33-0d629541ba48)

**Acceptance Criteria:**

- LEFT PANEL

- [x] List down all employees that need to be evaluated by the current user
- [x] Evaluees should be sorted by last_name and first_name in ascending order
- [x] No paging for the list of evaluees
- [x] By default, select the first item in the list
- [x] Display the Evaluee Name. Name should be `last_name, first_name` format
- [x] Display status of the evaluation (e.g. Draft, Submitted)
- [x] Display project name under the Evaluee Name
- [x] Display the role of the evaluee for that project
- [x] Display the duration the evaluee was assigned to that project (still needs to be added, not in the wireframe)
- [x] At this stage, evaluation.status can only either be Open, Ongoing or Submitted. If status = Open, font must be in bold (meaning the evaluator hasn't started yet on this evaluation). If status = Ongoing, use normal font. 

- MAIN PANEL

- [x] List the name of the criteria for evaluation 
- [x] At the bottom of the name, display the description
- [x] Based on answer type (in this case, 1), show the 5 point star rating
- [x] Display textbox where evaluator can input his comments

**Comment by emmaacha** [comment]
PR: #117

**Comment by sheilaramas** [comment]
OK Verified. Created separate ticket for enhancement requests.
