### ISSUE TITLE
Add menu link to open Performance Evaluation Screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#62]
**DESCRIPTION**

- [x] Add `Evaluations` link ni left menu panel.
- [ ] When clicked, this will open Performance Evaluation Form screen
- [x] This link will be available for all.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/67

**Comment by sheilaramas** [comment]
`When clicked, this will open Performance Evaluation Form screen ` will be changed.
When clicked, this will open evaluation administration list screen showing list of all active evaluations.
