### ISSUE TITLE
Landing page when accessing KH360 should be the LOGIN screen

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#68]
Currently, the following screen is displayed when I access KH360:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/e5e8f41b-1a03-41b2-bcc4-276a2e00bdd7)

It should automatically go to LOGIN screen.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/5dfbb386-6471-4c2b-a0ef-0c1964c0206b)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/73
