### ISSUE TITLE
Login Page - add KH logo

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#69]
**DESCRIPTION**

- [ ] Remove the text KaishaHero Login. 
- [ ] Add KH logo in the login page. Please refer to screenshot below for concept.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/117090ad-a322-43c2-989a-341e5b0af30e)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/74
