### ISSUE TITLE
Favicon - change to KH logo

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#70]
**DESCRIPTION**

Change default favicon.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/443757ad-4721-4c26-94a1-d639e4487f4a)

Use the KH logo.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/78b16f65-a1cb-4224-a77b-f2b214a18106)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/75
