### ISSUE TITLE
Font - Is it possible to follow font used on KaishaHero for consistency?

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#71]
**DESCRIPTION**

Currently, this is the font used:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/f833f33f-e8dc-4d43-91eb-cc6738f26b46)

Can we use this instead?

![Image](https://github.com/nerubia/kh360-react/assets/1640285/b5cbf889-77e8-4ae1-b8f0-f39a58565f82)

![Image](https://github.com/nerubia/kh360-react/assets/1640285/2cd7bde4-dd67-4697-8733-1cab90d6deed)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/77
