### ISSUE TITLE
Add External Evaluator - Required field error is still displaying even the field is already inputted

### ISSUE THREAD

**Issue by Acey06** [nerubia/kh360-react#726]
Steps:
1. Input all fields at least more than 100 chars
2. Click Save button
3. Clear the First name and Click save button

Actual:
- Required is still displaying if the 500 error is still responded

Note:

This issue is related to ticket [725](https://github.com/nerubia/kh360-react/issues/725)

https://github.com/nerubia/kh360-react/assets/26914098/e7b3f673-1b32-49b0-aaa2-211b3946c229

**Comment by emmaacha** [comment]
FE PR: #728 
BE PR: [#475](https://github.com/nerubia/kh360-nodejs/pull/475)

**Comment by Acey06** [comment]
Issue is no longer display since the ticket [725](https://github.com/nerubia/kh360-react/issues/725) is already fixed.
Moved to Done

https://github.com/nerubia/kh360-react/assets/26914098/6603fd46-d381-4d05-b74f-d3208ca5372a
