### ISSUE TITLE
Create Evaluation - Add a restriction on evaluee's evaluation period date

### ISSUE THREAD

**Issue by Acey06** [nerubia/kh360-react#753]
**Expected:**

- User should be able to select a date on Evaluation Period present or after the "Start Date" and present or before the "End Date" depend on Project Duration was set.
- If the user manually input or select a date before "Start Date" and the date after "End Date" of Project Duration set, it should be unacceptable.

**Actual SS:**

Project - Project Duration:

Note: Chad Augis has a longest time of project assignment

![image](https://github.com/nerubia/kh360-react/assets/26914098/676963f6-7a13-4fd3-b583-598c1806baf6)

Create Evaluation - Evaluation Period:

![image](https://github.com/nerubia/kh360-react/assets/26914098/1c289d6c-814d-413f-8b28-37cfda46adb2)

**Comment by gborgonia-ir** [comment]
Closing this ticket. This is not an issue.
