### ISSUE TITLE
View Evaluation Templates - no contents shown when viewing PM Evaluation by BOD Template

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#776]
**DESCRIPTION**

- [ ] No contents are displayed for this particular record. Can you please investigate why?

![Image](https://github.com/nerubia/kh360-react/assets/1640285/afbacfb9-227d-4391-96cb-54f731cf5cc4)

DB Data below:

![Image](https://github.com/nerubia/kh360-react/assets/1640285/793d97de-4983-49cd-847e-49e65f958207)

**Comment by emmaacha** [comment]
Eval Template Contents for this Evaluation Template was soft deleted, they have values in deleted_at
