### ISSUE TITLE
Create Performance Evaluation Step 2A - no search results found if I erase the inputted text in Name field then click on Search

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#79]
To replicate, do the following:
1. Input text in Name search filter (e.g. `an`)
2. Click on Search button. Search results will be displayed.
3. Manually erase the text entered in Name field (Do not use clear button)
4. Click on Search button.

Notice that when you click Search button, nothing happens.
Expected is that all results will be displayed since you cleared the text in Name filter.

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/81
