### ISSUE TITLE
Create Performance Evaluation Step 2A - Back Action

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-react#8]
**Wireframe**

![Image](https://github.com/nerubia/kh360-react/assets/54575305/b9140c66-c549-4124-915f-b5b77a2ddd9e)

**Description:**

> As an Admin
> I want to be able to go back to Step 1 of the creation process
> so that I can revert in case I made a mistake or redo the employee search

**Acceptance Criteria:**

- [x] When Back [ < ] button is clicked, display modal window showing a warning message as follows:

```
Are you sure you want to go back?
If you go back, your data won't be saved.

```

- [x] Below the message, show NO and YES buttons.
- [x] If NO is clicked, close the modal window
- [x] If YES is clicked, redirect to `Step1` Screen

**Comment by emmaacha** [comment]
PR: #26

**Comment by sheilaramas** [comment]
**COMMENTS**

- [ ] Can we change the title of the Modal Window to just `Go Back`

**Comment by emmaacha** [comment]
PR: #76

**Comment by sheilaramas** [comment]
- [ ] Please use `Go Back`

**Comment by emmaacha** [comment]
PR: #82
