### ISSUE TITLE
View Evaluation Administration - unresponsive UI

### ISSUE THREAD

**Issue by rrosel** [nerubia/kh360-react#824]
Actual - some columns will be cut out on large screen size.

![image](https://github.com/nerubia/kh360-react/assets/54173000/5f604826-49ba-4ed5-94cb-53632107bf23)

[Screenshare - 2024-03-01 11 54 48 AM.webm](https://github.com/nerubia/kh360-react/assets/54173000/4f14f3d0-b456-47e6-8de7-ea1b338b7d11)

Expected - add scroll bar to view the other columns. It should be responsive.

**Comment by rrosel** [comment]
**Not OK in Beta**

If possible, please display 1 scroll bar below the Evaluees table, not for each evaluee. 
![image](https://github.com/nerubia/kh360-react/assets/54173000/043cd119-4587-41eb-95e4-e28caac44870)

[Screenshare - 2024-03-01 4 57 38 PM.webm](https://github.com/nerubia/kh360-react/assets/54173000/3dd86999-9705-42ea-b95d-6d6c48359fc1)

**Comment by gborgonia-ir** [comment]
@rrosel scroll bar and table enhancement will be covered in this ticket. [#837](https://github.com/nerubia/kh360-react/issues/837)

**Comment by rrosel** [comment]
closing this ticket 
main ticket https://github.com/nerubia/kh360-react/issues/837
