### ISSUE TITLE
Step 2A - no employees should be selected by default for new records

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#85]
**DESCRIPTION**

- When I create a new evaluation administration and move to Step 2, there are employees that are selected by default. I think this is based on the selected employees from the previous evaluation administration record I created.
- By default, no employees should be selected

**STEPS TO REPLICATE**

1. Create Evaluation Administration (Eval 1)
2. In Step 2, select 1 employee (e.g. Anor, Darwin)
3. Click cancel and exit. You will be redirected back to Evaluation Administration list.
4. Click on `Create Evaluations` again to create a 2nd record.
5. Input data in Step 1 then proceed to Step 2.
6. In Step 2, notice that Anor, Darwin is preselected.

**Comment by emmaacha** [comment]
PR: #87
