### ISSUE TITLE
Eval Admin - Step 3 - Enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#89]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/34b93435-406c-4de7-9a2e-7b5e4b0674f4)

- [x] Right now, broken image is displayed if no image is set. Please use default image. (e.g. KH Logo)
- [x] Please use Purple font for screen title (same as what we used for other screens)
- [x] Can we use purple font for the names? Or with underline? We need to let the user know that these are clickable.
- [x] Can we decrease the size of the `x` at the upper right side? This also needs to be purple I think so user will know this is clickable?  Or maybe we can use a trash icon then it will now be centered vertically.
- [x] For status, can we put it in a box with different colors depending on status? (e.g. DRAFT is light grey, READY is green etc?)
- [x] Please do not use the RED color for CLEAR button. Use the button with purple outline, purple font with white background

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/95

**Comment by sheilaramas** [comment]
**REFERENCE ON COLORS FOR BADGES**



![Image](https://github.com/nerubia/kh360-react/assets/1640285/8893eca6-bc64-4a5d-8e55-4d343543fb56)
