### ISSUE TITLE
Create Performance Evaluation Step 2B - Review Employees Screen

### ISSUE THREAD

**Issue by Dev-Nino** [nerubia/kh360-react#9]
**Wireframe:**

![Image](https://github.com/nerubia/kh360-react/assets/54575305/94563af3-642c-44db-8fcc-d3958392016e)

**Acceptance Criteria:**

- [x] Under `Included` section, list all employees that were selected in previous step. Also show total number of employees in this section.
- [x] Under `Excluded` section, list all employees that were not selected. By default, this section is collapsed. Also show total number of employees in this section.
- [x] Employees should be sorted by last_name and first_name in ascending order
- [x] No pagination for this, just scrollbar.

- [x] Name column should be `last_name, first_name` format
- [x] Date started should be yyyy-mm-dd format
- [x] When you click SAVE and PROCEED, save data. 
            - If process is successful, redirect to Step 3
            - If process is not successful (e.g. did not pass validations), display modal error message

**Comment by emmaacha** [comment]
#34

**Comment by emmaacha** [comment]
PR: #39
