### ISSUE TITLE
Eval Admin - Step 2B Enhancements

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#92]
**DESCRIPTION**

![Image](https://github.com/nerubia/kh360-react/assets/1640285/0e73642a-880f-4b7a-a336-0171fdf01c62)

- [x] Use Purple font for screen title
- [x] Change ROLE column label to Position
- [x] For Employee type, please use Proper Casing (Same as the change we did for Step 2A)
- [x] By default, collapse excluded list
- [x] If date is not valid, please set as blank, do not use INVALID DATE

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/102
