### ISSUE TITLE
Eval Admin - Step 4 - Please use default image if no image set for employee

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#93]
**DESCRIPTION**

- [ ] Please use default image if no image is set for employee. Currently, broken image is displayed.

![Image](https://github.com/nerubia/kh360-react/assets/1640285/41c8fd06-870f-480e-a796-879d7ad6767f)

**Comment by jatnerubia** [comment]
PR: https://github.com/nerubia/kh360-react/pull/98
