### ISSUE TITLE
View Eval Admin - weird behavior with Employee List

### ISSUE THREAD

**Issue by sheilaramas** [nerubia/kh360-react#94]
**DESCRIPTION**

- [x] Sometimes, wrong list of employees are shown in the list. I think some of these are employees from previously viewed Eval Admin record. Please refer to recording below.

https://github.com/nerubia/kh360-react/assets/1640285/6e75cbed-498c-48d0-ac98-7fcb02058909

**Comment by emmaacha** [comment]
PR: #127

**Comment by sheilaramas** [comment]
OK Verified
